import Nav from "./components/Nav";
import moon from "./img/image-moon.png";

function App() {
  return (
    <section class='hero-bg'>
      
      <Nav />

      <div className='md:container px-2 pt-5 md:text-left text-center'>
        <h1 className='text-white pb-4 text-2xl'><span className='mr-2 font-bold text-[#ffffff7]'>01</span>PICK YOUR DESTINATION</h1>
      </div>

      <div className="md:flex items-center md:justify-between pt-6 mx-auto">
          <img src={moon} alt='moon' className="md:w-[36%] w-[52%] md:py-0 py-4  mx-auto" />
          <div className="md:w-1/2 mx-auto max-sm:text-center">
          <ul className="text-white pb-4">
            <li className="inline-block cursor-pointer md:mr-8 md:mx-0 mx-4 border-b-2">MOON</li>
            <li className="inline-block cursor-pointer md:mr-8 md:mx-0 mx-4 ">MARS</li>
            <li className="inline-block cursor-pointer md:mr-8 md:mx-0 mx-4 ">EUROPA</li>
            <li className="inline-block cursor-pointer md:mr-8 md:mx-0 mx-4 ">TITAN</li>
          </ul>

          <h1 className="text-white w-full font-Bellefair pb-2 text-7xl">MOON</h1> 
          <p className="text-[#d2d8f9] font-extralight text-sm md:w-2/3 md:pl-1 pb-10 leading-6 tracking-wide border-b-[0.5px] border-[#ffffff66]">webpack finds all relative module references in CSS (they start with ./) and replaces them with the final paths from the compiled bundle. If you make a typo or accidentally delete an important file, you will see a compilation error, like when you import a non-existent JavaScript module. The final filenames in the compiled bundle are generated by webpack from content hashes. If the file content changes in the future, webpack will give it a different name in production so you don’t need to worry about long-term caching of assets.</p>
          
          <div className='flex md:justify-between justify-around lg:w-1/2 w-auto pt-10'>
            <div>
            <span className='text-[#d2d8f6] text-sm'>Avg. Distance</span>
            <h1 className='text-3xl text-white'>384,400</h1>
            </div>

            <div>
            <span className='text-[#d2d8f6] text-sm'>Est. travel time</span>
            <h1 className='text-3xl text-white'>3 DAYS</h1>
            </div>
          </div>
          </div>

          
      </div>

      

    </section>
  );
}

export default App;

